### ISSUE TITLE
A couple of bugs with the sound menu and power applet

### ISSUE THREAD

**Issue by ravila4** [zagortenay333/numix-cinnamon#5]
1. Opening the sound menu, and clicking on "launch player" causes the player icons in the sub-menu to rescale themselves in an ugly way. This issue is not present in your Zukitwo theme.

2. The volume bar under the "Applications" sub-menu, which you get when right-clicking on the sound menu while a player is open doesn't slide all the way to the right. Again, not present in the Zukitwo theme.

3. The text in the power applet needs more padding because it is all bunched up together. I also saw this issue in the latest Zukitwo.

**Comment by zagortenay333** [comment]
Thx for reporting. It would be nice if you could open an issue for each problem respectively instead of reporting several issues in one.

I fixed all the above.

The slider issue seems to be a bug in cinnamon. I made a temporary fix and submited an issue: https://github.com/linuxmint/Cinnamon/issues/4830

**Comment by ravila4** [comment]
Thanks for your prompt fix, and my apologies for opening several issues in one. It's my first time reporting.
